source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'ECSlidingViewController', '~> 2.0.2'
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'SWTableViewCell', '~> 0.3.7'